// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxepywzxxmrcajhybael.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4ZXB5d3p4eG1yY2FqaHliYWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjExNjAsImV4cCI6MjA1ODczNzE2MH0.eLzS_96YSGwUP339W-SB5DxnGKg6JEtN0-bZHDNwKMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);